<a href="https://colab.research.google.com/github/ccn700/HW/blob/main/HW5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Array 1. Дано целое число N (> 0). Сформировать и вывести целочисленный массив размера N, содержащий N первых положительных нечетных чисел: 1, 3, 5, ... .

In [ ]:
import random
N = random.randrange(1,10)
print("N = ", N)
a1 = []
for i in range(N):
    a1.append(i*2+1)
print(a1)
a2 = [i*2+1 for i in range(N)]
print(a2)


N =  4
[1, 3, 5, 7]
[1, 3, 5, 7]


Array 2. Дано целое число N (> 0). Сформировать и вывести целочисленный массив размера N, содержащий степени двойки от первой до N-й: 2, 4, 8, 16, ... .

In [ ]:
import random
import math
N = random.randrange(1,10)
print("N = ", N)
a1 = []
p = 1
for i in range(N):
    p *= 2
    a1.append(p)
print(a1)
a2 = [int(math.pow(2,i+1)) for i in range(N)]
print(a2)

N =  4
[2, 4, 8, 16]
[2, 4, 8, 16]


Array 3. Дано целое число N (> 1), а также первый член A и разность D арифметической прогрессии. Сформировать и вывести массив размера N, со-держащий N первых членов данной прогрессии:
A,A+D,A+2⋅D,A+3⋅D,....

In [ ]:
import random
N = random.randrange(1,10)
A = random.randrange(-10,10)
D = round(random.uniform(-5,5),1)
print("N = ", N)
print("A = ", A)
print("D = ", D)
a1 = []
for i in range(N):
    x = A + i*D
    a1.append(x)
print(a1)
a2 = [A + i*D for i in range(N)]
print(a2)

N =  2
A =  -5
D =  4.9
[-5.0, -0.09999999999999964]
[-5.0, -0.09999999999999964]


Array 4. Дано целое число N (> 1), а также первый член A и знаменатель D геометрической прогрессии. Сформировать и вывести массив размера N, содержащий N первых членов данной прогрессии:
A,A⋅D,A⋅D2,A⋅D3,...
 .

In [ ]:
import random
import math
N = random.randrange(1,10)
A = random.randrange(-10,10)
D = round(random.randrange(-5,5),1)
print("N = ", N)
print("A = ", A)
print("D = ", D)
a1 = []
for i in range(N):
    x = A * (D**i)
    a1.append(x)
print(a1)
a2 = [A * (D**i) for i in range(N)]
print(a2)

N =  2
A =  2
D =  -4
[2, -8]
[2, -8]


Array 5. Дано целое число N (> 2). Сформировать и вывести целочисленный массив размера N, содержащий N первых элементов последовательности чисел Фибоначчи FK
:
F1=1,F2=1,FK=FK−2+FK−1,K=3,4,...
 .

In [ ]:
import random
import math
N = random.randrange(2,15)
print("N = ", N)
a = [1,1]
for i in range(2,N):
    x = a[i-2] + a[i-1]
    a.append(x)
print(a)

N =  13
[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233]


Matrix1. Даны целые положительные числа M и N. Сформировать целочисленную матрицу размера M×N
, у которой все элементы I-й строки имеют значение 10⋅I
 (I = 1, ..., M).

In [ ]:
import random
import numpy

M = random.randrange(2,10)
N = random.randrange(2,10)
print("M = ",M,"; N = ",N)
a = numpy.zeros((M, N))

print(a)

for i in range(M):
    for j in range(N):
        a[i][j] = (i+1)*10

print(a)

Matrix = [[(y+1)*10 for x in range(N)] for y in range(M)]
print(Matrix)

Matrix2. Даны целые положительные числа M и N. Сформировать целочисленную матрицу размера M×N
, у которой все элементы J-го столбца имеют значение 5⋅J
 (J = 1, ..., N).

In [ ]:
import random
import numpy
M = random.randrange(2,10)
N = random.randrange(2,10)
print("M = ",M,"; N = ",N)
a = numpy.zeros((M, N))
for i in range(M):
    for j in range(N):
        a[i][j] = (j+1)*5

print(a)
Matrix = [[(x+1)*5 for x in range(N)] for y in range(M)]
print(Matrix)

M =  8 ; N =  4
[[ 5. 10. 15. 20.]
 [ 5. 10. 15. 20.]
 [ 5. 10. 15. 20.]
 [ 5. 10. 15. 20.]
 [ 5. 10. 15. 20.]
 [ 5. 10. 15. 20.]
 [ 5. 10. 15. 20.]
 [ 5. 10. 15. 20.]]
[[5, 10, 15, 20], [5, 10, 15, 20], [5, 10, 15, 20], [5, 10, 15, 20], [5, 10, 15, 20], [5, 10, 15, 20], [5, 10, 15, 20], [5, 10, 15, 20]]


Matrix3. Даны целые положительные числа M, N и набор из M чисел. Сформировать матрицу размера M×N
, у которой в каждом столбце содержатся все числа из исходного набора (в том же порядке).

In [ ]:
import random
import numpy
M = random.randrange(2,10)
N = random.randrange(2,10)
print("M = ",M,"; N = ",N)
a = numpy.zeros((M, N))

c = [random.randrange(1,5) for i in range(M)]
print("Set of ",M," numbers:")
print(c)
for i in range(M):
    for j in range(N):
        a[i][j] = c[i]
print(a)
Matrix = []
for i in range(M):
    Matrix.append([c[i] for j in range(N)])
print(Matrix)

M =  3 ; N =  4
Set of  3  numbers:
[2, 1, 3]
[[2. 2. 2. 2.]
 [1. 1. 1. 1.]
 [3. 3. 3. 3.]]
[[2, 2, 2, 2], [1, 1, 1, 1], [3, 3, 3, 3]]


Matrix4. Даны целые положительные числа M, N и набор из N чисел. Сформировать матрицу размера M×N
, у которой в каждой строке содержатся все числа из исходного набора (в том же порядке).

In [ ]:
import random
import numpy
M = random.randrange(2,10)
N = random.randrange(2,10)
print("M = ",M,"; N = ",N)
a = numpy.zeros((M, N))

c = [random.randrange(1,5) for i in range(N)]
print("Набор из ",N," чисел:")
print(c)
print()
for i in range(M):
    for j in range(N):
        a[i][j] = c[j]
print(a)
print()
Matrix = [c for y in range(M)]
print(Matrix)

M =  5 ; N =  9
Набор из  9  чисел:
[2, 3, 4, 2, 2, 2, 1, 4, 3]

[[2. 3. 4. 2. 2. 2. 1. 4. 3.]
 [2. 3. 4. 2. 2. 2. 1. 4. 3.]
 [2. 3. 4. 2. 2. 2. 1. 4. 3.]
 [2. 3. 4. 2. 2. 2. 1. 4. 3.]
 [2. 3. 4. 2. 2. 2. 1. 4. 3.]]

[[2, 3, 4, 2, 2, 2, 1, 4, 3], [2, 3, 4, 2, 2, 2, 1, 4, 3], [2, 3, 4, 2, 2, 2, 1, 4, 3], [2, 3, 4, 2, 2, 2, 1, 4, 3], [2, 3, 4, 2, 2, 2, 1, 4, 3]]


Matrix5. Даны целые положительные числа M, N, число D и набор из M чисел. Сформировать матрицу размера M×N
, у которой первый столбец совпадает с исходным набором чисел, а элементы каждого следующего столбца равны сумме соответствующего элемента предыдущего столбца и числа D (в результате каждая строка матрицы будет содержать элементы арифметической прогрессии).

In [ ]:
import random
import numpy
M = random.randrange(2,10)
N = random.randrange(2,10)
D = random.randrange(-5,5)
print("M = ",M,"; N = ",N,"; D = ",D)
a = numpy.zeros((M, N))
c = [random.randrange(1,5) for i in range(M)]
print("Набор из ",M," чисел:")
print(c)
for i in range(M):
    for j in range(N):
        a[i][j] = c[i]+D*j
print(a)
Matrix = []
for i in range(M):
    Matrix.append([c[i]+D*j for j in range(N)])
print(Matrix)

M =  4 ; N =  7 ; D =  3
Набор из  4  чисел:
[2, 3, 3, 4]
[[ 2.  5.  8. 11. 14. 17. 20.]
 [ 3.  6.  9. 12. 15. 18. 21.]
 [ 3.  6.  9. 12. 15. 18. 21.]
 [ 4.  7. 10. 13. 16. 19. 22.]]
[[2, 5, 8, 11, 14, 17, 20], [3, 6, 9, 12, 15, 18, 21], [3, 6, 9, 12, 15, 18, 21], [4, 7, 10, 13, 16, 19, 22]]
